name: run app.py

on:
  schedule:
    - cron: '0 13 07 * *' # “At 12:00 on day-of-month 18.”

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute ipynb script # run app.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python Model_Keras_LSTM.ipynb
          
      - name: commit files
        run: |
          git config --local user.email "varrat.asanka@gmail.com"
          git config --local user.name "RoiJupiter"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
